# Generated by Django 3.2.9 on 2021-11-04 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211103_2329'),
        ('blog', '0006_auto_20211104_0857'),
    ]

    operations = [
    ]
