# Generated by Django 3.2.9 on 2022-01-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_merge_0006_auto_20211103_2329_0006_auto_20211104_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
