# Generated by Django 3.2.9 on 2022-02-03 00:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220202_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='disliked',
            field=models.ManyToManyField(blank=True, related_name='comment_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='comment_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
