# Generated by Django 3.2.9 on 2022-03-03 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20220225_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notofication_type',
            new_name='notification_type',
        ),
    ]
