# Generated by Django 3.2.8 on 2023-01-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rename_notofication_type_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='researcher_tags', to='blog.Tag'),
        ),
    ]
