# Generated by Django 3.2.8 on 2023-02-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20230209_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='institute',
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
    ]
