# Generated by Django 3.2.8 on 2023-02-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_profile_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_email_opt',
            field=models.BooleanField(default=True),
        ),
    ]
